### ISSUE TITLE
在不正常的时间点,毫无预兆的在catalina.out中报错,然后顺便让log4j的文件输出失效

### ISSUE THREAD

**Issue by Yionr** [Yionr/upload#3]
信息: 解析 HTTP 请求 header 错误
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: 在方法名称中发现无效的字符串, HTTP 方法名必须是有效的符号.
        at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:140)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1108)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Yionr** [comment]
稍微阅读了一下源码,对这个报错有了大概的了解,这个报错是因为 请求行中的方法名称有无效字符
具体无效字符为:控制符或者分隔符,具体在源码中详细定义了--⬇️
```
        for (int i = 0; i < ARRAY_SIZE; i++) {
            // Control> 0-31, 127
            if (i < 32 || i == 127) {
                IS_CONTROL[i] = true;
            }

            // Separator
            if (    i == '(' || i == ')' || i == '<' || i == '>'  || i == '@'  ||
                    i == ',' || i == ';' || i == ':' || i == '\\' || i == '\"' ||
                    i == '/' || i == '[' || i == ']' || i == '?'  || i == '='  ||
                    i == '{' || i == '}' || i == ' ' || i == '\t') {
                IS_SEPARATOR[i] = true;
            }
```
InternalInputBuffer.java:140行上下内容是这样的:

```
else if (!HttpParser.isToken(buf[pos])) {
                throw new IllegalArgumentException(sm.getString("iib.invalidmethod"));
            }
```
buf是在请求行中的一个一个字符,pos会一格一格累加,buf到时候所有元素加起来就是请求头中的一行的内容
token在这里代表方法名,token的验证方式就是 : `!IS_CONTROL[i] && !IS_SEPARATOR[i] && i < 128`
既然报错 指定在这一行,那说明 tomcat监测到了一个请求,这个请求的方法名字上有不正常的符号.比如正常的请求行是这样的`Host: localhost:8080` 那我猜测他这里,这个报错,指定的不正常的请求行是这样的: `((*^^&$*:xxx` ,下一步我将会去找东西模拟这个请求,看看和上面报错是否一模一样,再做之后的尝试,因为我现在不知道在什么情况下会出现这种符号(我的代码中绝对没有发送这个,而且出现这个报错的时间也是很不正常的,比如半夜1点3点,服tomcat刚刚启动完成突然在同一秒连续出现三次,在我的日志中都有记录)

**Comment by Yionr** [comment]
用了nginx之后 , 这个问题消失了
